themes_bootstrap:
    resource: "@ThemesBootstrapBundle/Resources/config/routing.yml"
    prefix:   /

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

inmueble:
    resource: "@InmuebleBundle/Resources/config/routing.yml"
    prefix:   /

inmueble_number:
    path:     /inmueble/number/{count}
    defaults: { _controller: AppBundle:Inmueble:number }
